// Daivadnya Samaj Bangalore — Demo data
const PX = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop`;

export const TEST_USERS = [
  {
    phone: "9876543210", otp: "121212",
    name: "Priya Kamat", role: "member",
    gotra: "Kashyap", native: "Bengaluru, Karnataka", avatar: "6",
  },
  {
    phone: "9999999999", otp: "121212",
    name: "Shri Narayanarao Shet", role: "elder",
    gotra: "Bharadwaja", native: "Kumta, Uttara Kannada", avatar: "elder",
  },
  {
    phone: "9871234567", otp: "121212",
    name: "Akhilesh Kamat", role: "member",
    gotra: "Kashyap", native: "Udupi, Karnataka", avatar: "4",
  },
];

// Daivadnya Samaj family — goldsmith lineage from Kundapura/Kumta, now rooted in Bengaluru
export const FAMILY_MEMBERS = [
  {
    id: "1",
    name: "Ramachandra Shet",
    status: "Late",
    gotra: "Kashyap",
    native: "Kundapura, Karnataka",
    relation: "Great Grandfather",
    avatar: "RS",
    occupation: "Master Goldsmith & Jeweller",
    birthYear: "1920",
    children: ["2", "3"],
  },
  {
    id: "2",
    name: "Savitribai Shet",
    status: "Late",
    gotra: "Kashyap",
    native: "Kundapura, Karnataka",
    relation: "Great Grandmother",
    avatar: "SS",
    occupation: "Homemaker & Samaj Seva",
    birthYear: "1925",
    spouse: "1",
    children: [],
    parent: "1",
  },
  {
    id: "3",
    name: "Venkatesh Kamat",
    status: "Active",
    gotra: "Bharadwaja",
    native: "Kumta, Uttara Kannada",
    relation: "Grandfather",
    avatar: "VK",
    occupation: "Retired Jewellery Business Owner",
    birthYear: "1952",
    parent: "1",
    children: ["4", "5"],
  },
  {
    id: "4",
    name: "Suresh Kamat",
    status: "Active",
    gotra: "Kashyap",
    native: "Udupi, Karnataka",
    relation: "Father",
    avatar: "SK",
    occupation: "Senior Software Engineer, Infosys, Bengaluru",
    birthYear: "1978",
    parent: "3",
    children: ["6"],
  },
  {
    id: "5",
    name: "Rekha Pai",
    status: "Active",
    gotra: "Bharadwaja",
    native: "Mangaluru, Karnataka",
    relation: "Aunt",
    avatar: "RP",
    occupation: "Principal, Kendriya Vidyalaya, Bengaluru",
    birthYear: "1975",
    parent: "3",
    children: [],
  },
  {
    id: "6",
    name: "Priya Kamat",
    status: "Active",
    gotra: "Kashyap",
    native: "Bengaluru, Karnataka",
    relation: "Self",
    avatar: "PK",
    occupation: "UX Designer, Razorpay, Bengaluru",
    birthYear: "1999",
    parent: "4",
    children: [],
  },
];

export const MATRIMONIAL_CANDIDATES = [
  {
    id: "ananya-k",
    name: "Ananya Kamath",
    age: 27,
    gender: "F",
    location: "Bengaluru",
    gotra: "Bharadwaja",
    education: "MBA Finance, IIM Bangalore",
    company: "HDFC Bank — Wealth Management",
    designation: "Assistant Vice President",
    income: "₹22–28L",
    height: "5'4\"",
    complexion: "Wheatish",
    familyType: "Joint",
    fatherOccupation: "Jeweller & Proprietor, Kamath Gold House, Commercial Street",
    motherOccupation: "Teacher, MES College, Bengaluru",
    siblings: "1 Younger Brother, B.Tech, PESIT Bengaluru",
    star: "Rohini",
    rashi: "Vrishabha",
    mangal: "No",
    gotraSurname: "Bharadwaja",
    timeOfBirth: "10:45 AM",
    partnerExpectations: [
      "Well-educated professional from Daivadnya Samaj",
      "Preferably based in Bengaluru or Karnataka",
      "Family values and respect for Samaj traditions",
      "Age preference: 28–32 years",
    ],
    about:
      "Raised in a traditional Daivadnya Samaj family in Basavanagudi, Bengaluru. I love Carnatic music, cooking authentic Malvani cuisine, and participating in Samaj cultural events every year. Looking for a life partner who values both heritage and growth.",
    verified: true,
    matrimonialFee: true,
    avatar: "AK",
    photo: PX(17184880),  // young Indian woman in traditional attire
  },
  {
    id: "rohit-s",
    name: "Rohit Shet",
    age: 30,
    gender: "M",
    location: "Bengaluru",
    gotra: "Kashyap",
    education: "B.Tech Computer Science, NIT Surathkal",
    company: "Wipro — Product Division",
    designation: "Senior Software Engineer",
    income: "₹20–25L",
    height: "5'10\"",
    complexion: "Wheatish",
    familyType: "Joint",
    fatherOccupation: "Proprietor, Shet Jewellers, Chickpete, Bengaluru",
    motherOccupation: "Homemaker",
    siblings: "1 Elder Sister, Married into Nayak family, Mangaluru",
    star: "Uttara Phalguni",
    rashi: "Kanya",
    mangal: "No",
    gotraSurname: "Kashyap",
    timeOfBirth: "08:20 AM",
    partnerExpectations: [
      "Working professional from Daivadnya Samaj",
      "Family-oriented and respects Samaj culture",
      "Comfortable with joint family in Bengaluru",
    ],
    about:
      "Born and raised in R.T. Nagar, Bengaluru. Our family has been in the jewellery business for three generations in Chickpete. I enjoy trekking in the Western Ghats and volunteering at Samaj community events. Looking for a partner who balances tradition with a modern outlook.",
    verified: true,
    matrimonialFee: false,
    avatar: "RS",
    photo: PX(3131428),   // young South Asian man
  },
  {
    id: "sneha-n",
    name: "Sneha Naik",
    age: 25,
    gender: "F",
    location: "Mangaluru",
    gotra: "Vasishtha",
    education: "CA (ICAI), B.Com St. Aloysius College, Mangaluru",
    company: "Deloitte India — Audit",
    designation: "Deputy Manager, Audit & Assurance",
    income: "₹18–22L",
    height: "5'3\"",
    complexion: "Fair",
    familyType: "Nuclear",
    fatherOccupation: "Senior Goldsmith, Naik & Sons Jewellers, Mangaluru",
    motherOccupation: "Homemaker",
    siblings: "1 Younger Brother, CA Articleship",
    star: "Ashwini",
    rashi: "Mesha",
    mangal: "Yes",
    gotraSurname: "Vasishtha",
    timeOfBirth: "02:30 PM",
    partnerExpectations: [
      "Mangalik preferred",
      "Willing to relocate to Bengaluru or Mangaluru",
      "Professionally qualified (CA / MBA / Engineer)",
    ],
    about:
      "A first-generation CA from a proud Daivadnya Samaj family from Mangaluru. Passionate about finance, Tulu folk arts, and cooking traditional Kundapur cuisine. Weekends are for temple visits and Samaj bhajans. I believe a strong marriage rests on shared cultural roots.",
    verified: true,
    matrimonialFee: true,
    avatar: "SN",
    photo: PX(29201034),  // young Indian woman
  },
  {
    id: "karthik-p",
    name: "Karthik Pai",
    age: 29,
    gender: "M",
    location: "Bengaluru",
    gotra: "Atreya",
    education: "MBA IIM Bangalore, B.E. R.V. College of Engineering",
    company: "Razorpay — Growth",
    designation: "Senior Product Manager",
    income: "₹32–38L",
    height: "5'9\"",
    complexion: "Wheatish",
    familyType: "Nuclear",
    fatherOccupation: "Advocate, Karnataka High Court, Bengaluru",
    motherOccupation: "Sanskrit Lecturer, Bengaluru University",
    siblings: "None",
    star: "Mrigashira",
    rashi: "Mithuna",
    mangal: "No",
    gotraSurname: "Atreya",
    timeOfBirth: "06:15 PM",
    partnerExpectations: [
      "Educated and independent-minded woman from the Samaj",
      "Based in or willing to move to Bengaluru",
      "Values Sanskrit, classical music, and Samaj traditions",
    ],
    about:
      "Raised in Jayanagar, Bengaluru — a true product of the Daivadnya Samaj diaspora. Product manager by day, Carnatic vocalist and Samaj committee volunteer by weekend. Deeply proud of my goldsmith heritage while thriving in the startup world. Looking for a life partner who loves both heritage and adventure.",
    verified: true,
    matrimonialFee: false,
    avatar: "KP",
    photo: PX(1856477),   // young Indian man
  },
];

export const WELFARE_CAMPAIGNS = [
  {
    id: "samaj-bhavan",
    title: "Samaj Bhavan Renovation",
    category: "Infrastructure",
    description:
      "Renovation and expansion of the Daivadnya Samaj Bhavan in Basavanagudi, Bengaluru — adding a 500-seat auditorium, digital library, and modern kitchen for community feasts.",
    goal: 5000000,
    raised: 4250000,
    daysLeft: 12,
    backers: 328,
    image: "🏛️",
    color: "from-green-800 to-green-600",
  },
  {
    id: "annual-samaja-function",
    title: "Annual Samaja Utsava 2025",
    category: "Cultural Heritage",
    description:
      "Funding for the flagship annual Samaj cultural event: classical Carnatic & Tulu performances, elder felicitation, Samaj talent showcase, and merit scholarships for 50 students.",
    goal: 2500000,
    raised: 2000000,
    daysLeft: 28,
    backers: 214,
    image: "🪔",
    color: "from-amber-800 to-amber-600",
  },
  {
    id: "student-scholarship",
    title: "Daivadnya Vidya Nidhi — Scholarships",
    category: "Education",
    description:
      "Merit-cum-need scholarships for Samaj students pursuing engineering, medicine, and law. 30 scholarships of ₹50,000 each for the academic year 2025–26.",
    goal: 1500000,
    raised: 875000,
    daysLeft: 45,
    backers: 167,
    image: "🎓",
    color: "from-blue-900 to-blue-700",
  },
];

export const DASHBOARD_ACTIVITY = [
  {
    id: 1,
    user: "Venkatesh Kamat",
    action: "shared a memory",
    detail: '"1968 Samaj Utsava in Kumta"',
    time: "2 hours ago",
    type: "archive",
    avatar: "VK",
    photo: PX(2601464),
  },
  {
    id: 2,
    user: "Shri Narayanarao Shet",
    action: "verified the lineage of",
    detail: "Rohit Shet — Chickpete branch",
    time: "Yesterday",
    type: "tree",
    avatar: "NS",
    photo: PX(17815020),
  },
  {
    id: 3,
    user: "Rekha Pai",
    action: "has a birthday today!",
    detail: "Wishing her from the Samaj 🎉",
    time: "Today",
    type: "birthday",
    avatar: "RP",
    photo: PX(34515496),
  },
];

export const ELDER_QUEUE = [
  {
    id: "arjun-s",
    name: "Arjun Shenoy",
    claimingFrom: "Kundapura Branch (Udupi District)",
    relation: "Grandson of Late Govind Shenoy (Kundapura)",
    hasDocument: true,
    vouches: 2,
    avatar: "AS",
  },
  {
    id: "divya-n",
    name: "Divya Nayak",
    claimingFrom: "Kumta Branch (Uttara Kannada)",
    relation: "Daughter of Prakash Nayak (3 elder vouches pending)",
    hasDocument: false,
    hasPhoto: true,
    vouches: 3,
    avatar: "DN",
  },
];

// ── Community Members directory — 24 verified Daivadnya Samaj members ──────────
export const COMMUNITY_MEMBERS = [
  // Kundapura Branch
  { id: "m1",  name: "Gopalakrishna Shet",  age: 68, gender: "M", branch: "Kundapura",  gotra: "Kashyap",     occupation: "Retired Master Goldsmith",           location: "Kundapura, Udupi",         status: "Active",   verified: true,  joinedYear: 2019, photo: PX(4053536)  },
  { id: "m2",  name: "Mangala Shet",         age: 64, gender: "F", branch: "Kundapura",  gotra: "Kashyap",     occupation: "Homemaker & Samaj Seva",             location: "Kundapura, Udupi",         status: "Active",   verified: true,  joinedYear: 2019, photo: PX(11138457) },
  { id: "m3",  name: "Ganesh Shet",          age: 42, gender: "M", branch: "Kundapura",  gotra: "Kashyap",     occupation: "Jewellery Business Owner",           location: "Kundapura, Udupi",         status: "Active",   verified: true,  joinedYear: 2021, photo: PX(2601464)  },
  { id: "m4",  name: "Rupa Shet",            age: 65, gender: "F", branch: "Kundapura",  gotra: "Vasishtha",   occupation: "Retired School Teacher",             location: "Kundapura, Udupi",         status: "Active",   verified: true,  joinedYear: 2020, photo: PX(29201034) },
  { id: "m5",  name: "Akash Shet",           age: 19, gender: "M", branch: "Kundapura",  gotra: "Kashyap",     occupation: "Engineering Student, NIT Surathkal", location: "Kundapura, Udupi",         status: "Active",   verified: false, joinedYear: 2025, photo: PX(7345266)  },
  // Kumta Branch
  { id: "m6",  name: "Vasudeva Kamath",      age: 57, gender: "M", branch: "Kumta",      gotra: "Bharadwaja",  occupation: "Chartered Accountant (Own Practice)", location: "Kumta, Uttara Kannada",    status: "Active",   verified: true,  joinedYear: 2018, photo: PX(5746790)  },
  { id: "m7",  name: "Savita Pai",           age: 52, gender: "F", branch: "Kumta",      gotra: "Atreya",      occupation: "Principal, Govt. High School, Kumta", location: "Kumta, Uttara Kannada",    status: "Active",   verified: true,  joinedYear: 2018, photo: PX(30004176) },
  { id: "m8",  name: "Deepak Kamath",        age: 31, gender: "M", branch: "Kumta",      gotra: "Bharadwaja",  occupation: "Software Engineer, Infosys, Pune",    location: "Kumta / Pune",             status: "Active",   verified: true,  joinedYear: 2022, photo: PX(3131428)  },
  { id: "m9",  name: "Nandini Kamath",       age: 27, gender: "F", branch: "Kumta",      gotra: "Bharadwaja",  occupation: "CA Articleship, Bengaluru",           location: "Bengaluru, Karnataka",     status: "Active",   verified: false, joinedYear: 2024, photo: PX(17184880) },
  // Mangaluru Branch
  { id: "m10", name: "Ravi Kumar Shet",      age: 50, gender: "M", branch: "Mangaluru",  gotra: "Kashyap",     occupation: "Textile Merchant, Hampankatta",       location: "Mangaluru, Karnataka",     status: "Active",   verified: true,  joinedYear: 2017, photo: PX(17815020) },
  { id: "m11", name: "Sumitra Shet",         age: 47, gender: "F", branch: "Mangaluru",  gotra: "Kashyap",     occupation: "General Physician, KMC Hospital",     location: "Mangaluru, Karnataka",     status: "Active",   verified: true,  joinedYear: 2017, photo: PX(7485047)  },
  { id: "m12", name: "Girish Pai",           age: 44, gender: "M", branch: "Mangaluru",  gotra: "Atreya",      occupation: "Advocate, Karnataka High Court",      location: "Mangaluru, Karnataka",     status: "Active",   verified: true,  joinedYear: 2020, photo: PX(1856477)  },
  { id: "m13", name: "Pooja Rai",            age: 29, gender: "F", branch: "Mangaluru",  gotra: "Vasishtha",   occupation: "HR Manager, TCS Mangaluru",           location: "Mangaluru, Karnataka",     status: "Active",   verified: true,  joinedYear: 2023, photo: PX(34515496) },
  // Bengaluru Branch
  { id: "m14", name: "Narayana Kamat",       age: 62, gender: "M", branch: "Bengaluru",  gotra: "Bharadwaja",  occupation: "Retired IAS Officer",                location: "Bengaluru, Karnataka",     status: "Active",   verified: true,  joinedYear: 2016, photo: PX(4053536)  },
  { id: "m15", name: "Lakshmi Kamat",        age: 58, gender: "F", branch: "Bengaluru",  gotra: "Kashyap",     occupation: "Sanskrit Lecturer, Bengaluru Univ.", location: "Bengaluru, Karnataka",     status: "Active",   verified: true,  joinedYear: 2016, photo: PX(11138457) },
  { id: "m16", name: "Vivek Kamath",         age: 35, gender: "M", branch: "Bengaluru",  gotra: "Bharadwaja",  occupation: "Product Manager, Flipkart",           location: "Bengaluru, Karnataka",     status: "Active",   verified: true,  joinedYear: 2022, photo: PX(2601464)  },
  { id: "m17", name: "Tejaswini Shet",       age: 32, gender: "F", branch: "Bengaluru",  gotra: "Kashyap",     occupation: "UI/UX Designer, Myntra",              location: "Bengaluru, Karnataka",     status: "Active",   verified: true,  joinedYear: 2023, photo: PX(7485047)  },
  { id: "m18", name: "Rajesh Pai",           age: 47, gender: "M", branch: "Bengaluru",  gotra: "Atreya",      occupation: "Entrepreneur, Pai Jewels Pvt. Ltd.",  location: "Bengaluru, Karnataka",     status: "Active",   verified: true,  joinedYear: 2019, photo: PX(5746790)  },
  { id: "m19", name: "Kavitha Nayak",        age: 55, gender: "F", branch: "Bengaluru",  gotra: "Vasishtha",   occupation: "Principal, Kendriya Vidyalaya",       location: "Bengaluru, Karnataka",     status: "Active",   verified: true,  joinedYear: 2018, photo: PX(30004176) },
  { id: "m20", name: "Yash Kamath",          age: 23, gender: "M", branch: "Bengaluru",  gotra: "Bharadwaja",  occupation: "B.Tech Student, RV College",          location: "Bengaluru, Karnataka",     status: "Active",   verified: false, joinedYear: 2025, photo: PX(7345266)  },
  { id: "m21", name: "Usha Pai",             age: 43, gender: "F", branch: "Bengaluru",  gotra: "Atreya",      occupation: "Gynecologist, Manipal Hospital",      location: "Bengaluru, Karnataka",     status: "Active",   verified: true,  joinedYear: 2020, photo: PX(17184880) },
  // Udupi Branch
  { id: "m22", name: "Subramanya Bhat",      age: 70, gender: "M", branch: "Udupi",      gotra: "Kashyap",     occupation: "Retired Bank Manager, SBI",          location: "Udupi, Karnataka",         status: "Active",   verified: true,  joinedYear: 2015, photo: PX(17815020) },
  { id: "m23", name: "Parvati Bhat",         age: 67, gender: "F", branch: "Udupi",      gotra: "Kashyap",     occupation: "Homemaker & Temple Trustee",         location: "Udupi, Karnataka",         status: "Active",   verified: true,  joinedYear: 2015, photo: PX(29201034) },
  // Out-of-State
  { id: "m24", name: "Sudarshan Pai",        age: 55, gender: "M", branch: "Out-of-State","gotra": "Atreya",   occupation: "Mechanical Engineer, Pune",           location: "Pune, Maharashtra",        status: "Active",   verified: true,  joinedYear: 2021, photo: PX(1856477)  },
];

// ── Verification Requests — 10 detailed pending records (of 24 total) ──────────
export const VERIFICATION_REQUESTS = [
  {
    id: "arjun-s",
    name: "Arjun Shenoy",
    age: 28,
    gender: "M",
    photo: PX(7345266),
    location: "Bengaluru, Karnataka",
    phone: "98765 ••••••",
    claimingFrom: "Kundapura Branch (Udupi District)",
    claimingAncestor: "Late Govind Shenoy (Kundapura, 1938–2012)",
    relation: "Grandson — father: Mohan Shenoy (not yet registered in system)",
    submittedOn: "12 May 2026",
    aadhaarStatus: "Verified",
    hasDocument: true,
    hasPhoto: true,
    documents: ["Aadhaar Card", "Birth Certificate", "Parents' Marriage Certificate"],
    vouches: 2,
    vouchesRequired: 3,
    vouchDetails: [
      { name: "Shri Narayanarao Shet",  role: "Elder, Kumta Branch",        status: "Approved" },
      { name: "Venkatesh Kamath",       role: "Member, Kundapura Branch",   status: "Approved" },
      { name: "Elder Sub-committee",    role: "3rd vouch required",         status: "Pending"  },
    ],
    lineageNotes: "Father Mohan Shenoy is not yet registered. Cross-reference with Kundapura branch records from 1982 recommended before final approval.",
    riskLevel: "low",
    status: "pending",
    occupation: "Software Developer, Accenture",
    gotra: "Kashyap",
  },
  {
    id: "divya-n",
    name: "Divya Nayak",
    age: 26,
    gender: "F",
    photo: PX(30004176),
    location: "Kumta, Uttara Kannada",
    phone: "97712 ••••••",
    claimingFrom: "Kumta Branch (Uttara Kannada)",
    claimingAncestor: "Prakash Nayak (Kumta, registered member since 2018)",
    relation: "Daughter of Prakash Nayak — birth certificate submitted",
    submittedOn: "10 May 2026",
    aadhaarStatus: "Pending",
    hasDocument: false,
    hasPhoto: true,
    documents: ["Photo Proof (Selfie with Prakash Nayak)", "School Leaving Certificate"],
    vouches: 3,
    vouchesRequired: 3,
    vouchDetails: [
      { name: "Vasudeva Kamath",        role: "Elder, Kumta Branch",        status: "Approved" },
      { name: "Savita Pai",             role: "Member, Kumta Branch",       status: "Approved" },
      { name: "Shri Narayanarao Shet",  role: "Elder, Committee Head",      status: "Approved" },
    ],
    lineageNotes: "All 3 vouches confirmed. Aadhaar upload pending from applicant. Can proceed to conditional approval while Aadhaar is uploaded.",
    riskLevel: "low",
    status: "pending",
    occupation: "B.Com Student, SDM College, Kumta",
    gotra: "Vasishtha",
  },
  {
    id: "mahesh-k",
    name: "Mahesh Kamath",
    age: 45,
    gender: "M",
    photo: PX(5746790),
    location: "Bengaluru, Karnataka",
    phone: "99001 ••••••",
    claimingFrom: "Mangaluru Branch",
    claimingAncestor: "Late Krishnarao Kamath (Mangaluru, 1930–1998)",
    relation: "Grandson via father Ramesh Kamath (deceased, 1967–2019)",
    submittedOn: "08 May 2026",
    aadhaarStatus: "Verified",
    hasDocument: true,
    hasPhoto: false,
    documents: ["Aadhaar Card", "Father's Death Certificate", "Ancestral Property Paper mentioning lineage"],
    vouches: 1,
    vouchesRequired: 3,
    vouchDetails: [
      { name: "Ravi Kumar Shet",        role: "Member, Mangaluru Branch",   status: "Approved" },
      { name: "Elder Sub-committee",    role: "2nd vouch required",         status: "Pending"  },
      { name: "Elder Sub-committee",    role: "3rd vouch required",         status: "Pending"  },
    ],
    lineageNotes: "Ancestral property record references Krishnarao Kamath as goldsmith in Mangaluru, 1960s. Father's branch not found in registry. Requires deeper genealogical audit.",
    riskLevel: "medium",
    status: "pending",
    occupation: "IT Manager, Wipro, Bengaluru",
    gotra: "Kashyap",
  },
  {
    id: "preethi-s",
    name: "Preethi Shet",
    age: 23,
    gender: "F",
    photo: PX(17184880),
    location: "Bengaluru, Karnataka",
    phone: "90081 ••••••",
    claimingFrom: "Bengaluru Branch (First Registration)",
    claimingAncestor: "Sudhir Shet (father, registered member m10)",
    relation: "Daughter of Sudhir Shet — direct first-time registration",
    submittedOn: "14 May 2026",
    aadhaarStatus: "Verified",
    hasDocument: true,
    hasPhoto: true,
    documents: ["Aadhaar Card", "Birth Certificate", "College ID"],
    vouches: 0,
    vouchesRequired: 2,
    vouchDetails: [
      { name: "Elder Sub-committee",    role: "1st vouch required",         status: "Pending" },
      { name: "Elder Sub-committee",    role: "2nd vouch required",         status: "Pending" },
    ],
    lineageNotes: "Fresh registration. Father Sudhir Shet already in system. Simplest case — just needs elder vouch formality.",
    riskLevel: "low",
    status: "pending",
    occupation: "B.Tech Final Year, PES University",
    gotra: "Kashyap",
  },
  {
    id: "varun-n",
    name: "Varun Nayak",
    age: 31,
    gender: "M",
    photo: PX(3131428),
    location: "Singapore (NRI)",
    phone: "+65 9••• ••••",
    claimingFrom: "Kundapura Branch (NRI)",
    claimingAncestor: "Suresh Nayak (Kundapura, registered member m4)",
    relation: "Son of Suresh Nayak — currently based in Singapore",
    submittedOn: "05 May 2026",
    aadhaarStatus: "Mismatch",
    hasDocument: true,
    hasPhoto: true,
    documents: ["Aadhaar Card (old address)", "Singapore PR Card", "Suresh Nayak's letter of confirmation"],
    vouches: 2,
    vouchesRequired: 3,
    vouchDetails: [
      { name: "Gopalakrishna Shet",     role: "Elder, Kundapura Branch",    status: "Approved" },
      { name: "Suresh Nayak",          role: "Parent (self-declared)",      status: "Approved" },
      { name: "Elder Sub-committee",    role: "NRI verification required",   status: "Pending"  },
    ],
    lineageNotes: "Aadhaar address mismatch — old Karnataka address vs Singapore residency. NRI members need special committee clearance as per 2023 policy update.",
    riskLevel: "medium",
    status: "pending",
    occupation: "Senior Software Engineer, Grab (Singapore)",
    gotra: "Vasishtha",
  },
  {
    id: "nalini-b",
    name: "Nalini Bhat",
    age: 37,
    gender: "F",
    photo: PX(34515496),
    location: "Udupi, Karnataka",
    phone: "94496 ••••••",
    claimingFrom: "Udupi Branch",
    claimingAncestor: "Late Ananth Bhat (Udupi, 1892–1954) — disputed record",
    relation: "Great-granddaughter via oral lineage (disputed)",
    submittedOn: "01 May 2026",
    aadhaarStatus: "Verified",
    hasDocument: true,
    hasPhoto: false,
    documents: ["Aadhaar Card", "Handwritten family record (1940s)", "Temple prasad receipt with family name"],
    vouches: 0,
    vouchesRequired: 3,
    vouchDetails: [
      { name: "Elder Sub-committee",    role: "1st vouch required",         status: "Pending" },
      { name: "Elder Sub-committee",    role: "2nd vouch required",         status: "Pending" },
      { name: "Elder Sub-committee",    role: "3rd vouch required",         status: "Pending" },
    ],
    lineageNotes: "⚠ High caution — Ananth Bhat (1892–1954) has a flagged duplicate conflict between Mysore and Bangalore branches. This claim should be frozen until the duplicate is resolved. Refer to Tree Alert #AK412.",
    riskLevel: "high",
    status: "pending",
    occupation: "Medical Lab Technician, Manipal Hospital, Udupi",
    gotra: "Kashyap",
  },
  {
    id: "kamala-k",
    name: "Kamala Kamath",
    age: 67,
    gender: "F",
    photo: PX(11138457),
    location: "Udupi, Karnataka",
    phone: "98443 ••••••",
    claimingFrom: "Udupi Branch (Late Registration)",
    claimingAncestor: "Subramanya Bhat (registered member m22)",
    relation: "Sister-in-law of Subramanya Bhat — late registration (previously unregistered)",
    submittedOn: "28 Apr 2026",
    aadhaarStatus: "Verified",
    hasDocument: true,
    hasPhoto: true,
    documents: ["Aadhaar Card", "Ration Card (1985, family name matches)", "Letter from Subramanya Bhat"],
    vouches: 3,
    vouchesRequired: 3,
    vouchDetails: [
      { name: "Subramanya Bhat",        role: "Member, Udupi Branch",       status: "Approved" },
      { name: "Shri Narayanarao Shet",  role: "Elder, Committee Head",      status: "Approved" },
      { name: "Parvati Bhat",          role: "Member, Udupi Branch",       status: "Approved" },
    ],
    lineageNotes: "All vouches cleared. This is a routine late-registration case. Elder committee has verbally approved — formal sign-off pending in system.",
    riskLevel: "low",
    status: "pending",
    occupation: "Retired, Temple Committee Volunteer",
    gotra: "Kashyap",
  },
  {
    id: "rakshit-s",
    name: "Rakshit Shet",
    age: 21,
    gender: "M",
    photo: PX(1856477),
    location: "Bengaluru, Karnataka",
    phone: "91008 ••••••",
    claimingFrom: "Bengaluru Branch",
    claimingAncestor: "Ganesh Shet (father, registered member m3)",
    relation: "Son of Ganesh Shet — student first-time registration",
    submittedOn: "02 May 2026",
    aadhaarStatus: "Verified",
    hasDocument: true,
    hasPhoto: true,
    documents: ["Aadhaar Card", "College Enrollment Certificate (MSRIT)", "Parent consent form"],
    vouches: 1,
    vouchesRequired: 2,
    vouchDetails: [
      { name: "Ganesh Shet",            role: "Parent (registered member)", status: "Approved" },
      { name: "Elder Sub-committee",    role: "2nd vouch required",         status: "Pending"  },
    ],
    lineageNotes: "Minor note: applicant is 21. Routine student registration. Father already a verified member. Quick formality.",
    riskLevel: "low",
    status: "pending",
    occupation: "B.E. Student, MSRIT, Bengaluru",
    gotra: "Kashyap",
  },
  {
    id: "swathi-p",
    name: "Swathi Pai",
    age: 29,
    gender: "F",
    photo: PX(29201034),
    location: "Bengaluru, Karnataka",
    phone: "87654 ••••••",
    claimingFrom: "Bengaluru Branch (Name Change)",
    claimingAncestor: "Rajesh Pai (father, registered member m18)",
    relation: "Daughter of Rajesh Pai — name change update after marriage into Nayak family",
    submittedOn: "06 May 2026",
    aadhaarStatus: "Verified",
    hasDocument: true,
    hasPhoto: true,
    documents: ["Marriage Certificate", "New Aadhaar (post name change)", "Gazette notification"],
    vouches: 2,
    vouchesRequired: 2,
    vouchDetails: [
      { name: "Rajesh Pai",             role: "Parent (registered member)", status: "Approved" },
      { name: "Usha Pai",              role: "Family member (registered)",  status: "Approved" },
    ],
    lineageNotes: "Name change — updating registry entry from 'Swathi Pai' to 'Swathi Nayak (née Pai)'. All documents clear.",
    riskLevel: "low",
    status: "pending",
    occupation: "HR Executive, Bengaluru",
    gotra: "Atreya",
  },
  {
    id: "sudarshan-p",
    name: "Sudarshan Pai",
    age: 55,
    gender: "M",
    photo: PX(2601464),
    location: "Pune, Maharashtra",
    phone: "98220 ••••••",
    claimingFrom: "Out-of-State Branch",
    claimingAncestor: "Late Vishwanath Pai (Kumta, 1948–2010)",
    relation: "Son of Late Vishwanath Pai — relocated to Pune in 1995",
    submittedOn: "25 Apr 2026",
    aadhaarStatus: "Verified",
    hasDocument: true,
    hasPhoto: false,
    documents: ["Aadhaar Card (Pune address)", "Father's Kumta property record", "Samaj membership from Pune Daivadnya chapter"],
    vouches: 2,
    vouchesRequired: 3,
    vouchDetails: [
      { name: "Vasudeva Kamath",        role: "Elder, Kumta Branch",        status: "Approved" },
      { name: "Deepak Kamath",         role: "Member, Kumta Branch",       status: "Approved" },
      { name: "Elder Sub-committee",    role: "3rd vouch from HQ required", status: "Pending"  },
    ],
    lineageNotes: "Out-of-state case. Pune Daivadnya chapter has given informal clearance. Kumta branch vouches match lineage records. One HQ elder vouch pending.",
    riskLevel: "low",
    status: "pending",
    occupation: "Mechanical Engineer, Thermax, Pune",
    gotra: "Atreya",
  },
];

// ── Invitation Route Planner families — Bengaluru Daivadnya Samaj ─────────────
export const INVITATION_FAMILIES = [
  {
    id: "if1",
    name: "Venkatesh Kamath",
    relation: "Grandfather · Bharadwaja Gotra",
    address: "12, Saraswathipuram, Basavanagudi, Bengaluru — 560004",
    area: "Basavanagudi",
    lat: 12.9419,
    lng: 77.5732,
    photo: PX(2601464),
    phone: "+91 98765 43210",
    note: "Prefers morning visits before 11 AM. Please bring prasad from the Samaj temple.",
    estimatedVisit: "45 min",
  },
  {
    id: "if2",
    name: "Rekha Pai",
    relation: "Aunt · Bharadwaja Gotra",
    address: "34, 4th Cross, Jayanagar 3rd Block, Bengaluru — 560011",
    area: "Jayanagar",
    lat: 12.9279,
    lng: 77.5803,
    photo: PX(34515496),
    phone: "+91 97712 34567",
    note: "She is usually home all day. Loves traditional Samaj sweets — bring chirote.",
    estimatedVisit: "30 min",
  },
  {
    id: "if3",
    name: "Narayana Kamat",
    relation: "Elder · Retired IAS Officer",
    address: "8, Margosa Road, Malleswaram, Bengaluru — 560003",
    area: "Malleswaram",
    lat: 13.0037,
    lng: 77.5662,
    photo: PX(4053536),
    phone: "+91 99001 56789",
    note: "Senior member. Keep visit under 1 hour. He's part of the invitation committee.",
    estimatedVisit: "60 min",
  },
  {
    id: "if4",
    name: "Suresh Kamat",
    relation: "Father · Kashyap Gotra",
    address: "22, 80 Feet Road, Indiranagar 1st Stage, Bengaluru — 560038",
    area: "Indiranagar",
    lat: 12.9784,
    lng: 77.6408,
    photo: PX(5746790),
    phone: "+91 98443 12345",
    note: "Weekday evenings or weekends best. Confirm one day before visiting.",
    estimatedVisit: "40 min",
  },
  {
    id: "if5",
    name: "Kavitha Nayak",
    relation: "Community Member · Vasishtha Gotra",
    address: "16, 7th Cross, Banashankari 2nd Stage, Bengaluru — 560070",
    area: "Banashankari",
    lat: 12.9243,
    lng: 77.5455,
    photo: PX(30004176),
    phone: "+91 94496 67890",
    note: "Schoolteacher — best reached on weekends. Family of 5 will attend the function.",
    estimatedVisit: "35 min",
  },
  {
    id: "if6",
    name: "Rajesh Pai",
    relation: "Community Member · Atreya Gotra",
    address: "45, Jyoti Nivas College Road, Koramangala 5th Block, Bengaluru — 560095",
    area: "Koramangala",
    lat: 12.9352,
    lng: 77.6245,
    photo: PX(1856477),
    phone: "+91 90081 34567",
    note: "Entrepreneur — flexible timings. Family of 4. Has offered car-pooling for elders.",
    estimatedVisit: "25 min",
  },
  {
    id: "if7",
    name: "Priya Kamat",
    relation: "Self · Kashyap Gotra",
    address: "18, 6th Main, RT Nagar, Bengaluru — 560032",
    area: "RT Nagar",
    lat: 13.0228,
    lng: 77.5978,
    photo: PX(7485047),
    phone: "+91 98765 43210",
    note: "Starting point. Collect invitations from here before the route.",
    estimatedVisit: "—",
  },
  {
    id: "if8",
    name: "Shri Narayanarao Shet",
    relation: "Elder & Admin · Bharadwaja Gotra",
    address: "3, Kumta House Colony, Rajajinagar, Bengaluru — 560010",
    area: "Rajajinagar",
    lat: 12.9906,
    lng: 77.5512,
    photo: PX(17815020),
    phone: "+91 99999 99999",
    note: "Head of Elder Sub-committee. Must be first on the route — most senior member.",
    estimatedVisit: "60 min",
  },
];
