// /Users/abhijeet/Documents/family-tree/app/src/lib/data.ts

export const TEST_USERS = [
  { phone: "9876543210", otp: "121212", name: "Aditi Rao", role: "member", gotra: "Kashyap", native: "Udupi, Karnataka", avatar: "AR" },
  { phone: "9999999999", otp: "121212", name: "Shri Raghavan", role: "elder", gotra: "Bharadwaja", native: "Bengaluru", avatar: "SR" },
  { phone: "9871234567", otp: "121212", name: "Ananya Sharma", role: "member", gotra: "Bharadwaja", native: "New Delhi", avatar: "AS" },
]

export const FAMILY_MEMBERS = [
  { id: "1", name: "Ramachandra Bhat", status: "Late", gotra: "Kashyap", native: "Kundapura", relation: "Great Grandfather", avatar: "RB", children: ["2","3"] },
  { id: "2", name: "Savitri Bhat", status: "Late", gotra: "Kashyap", native: "Kundapura", relation: "Great Grandmother", avatar: "SB", spouse: "1", children: [] },
  { id: "3", name: "Venkatesh Bhat", status: "Active", gotra: "Bharadwaja", native: "Kumta, Karnataka", relation: "Grandfather", avatar: "VB", parent: "1", children: ["4","5"] },
  { id: "4", name: "Rajesh Kumar Sharma", status: "Active", gotra: "Kashyap", native: "Udupi, Karnataka", relation: "Father", avatar: "RK", parent: "3", children: ["6"] },
  { id: "5", name: "Meera Kulkarni", status: "Active", gotra: "Bharadwaja", native: "Hubli, Karnataka", relation: "Aunt", avatar: "MK", parent: "3", children: [] },
  { id: "6", name: "Aditi Rao", status: "Active", gotra: "Kashyap", native: "Bengaluru, Karnataka", relation: "Self", avatar: "AR", parent: "4", children: [] },
]

export const MATRIMONIAL_CANDIDATES = [
  {
    id: "ananya-v",
    name: "Ananya V.",
    age: 27,
    gender: "F",
    location: "New Delhi",
    gotra: "Bharadwaja",
    education: "MBA Finance, FMS Delhi University",
    company: "Goldman Sachs",
    designation: "Senior Financial Analyst",
    income: "₹25–30L",
    height: "5'5\"",
    complexion: "Fair",
    familyType: "Nuclear",
    fatherOccupation: "Senior Cardiologist, AIIMS",
    motherOccupation: "Principal, DPS New Delhi",
    siblings: "1 Younger Brother, B.Tech IIT Kanpur",
    star: "Rohini",
    rashi: "Vrishabha",
    mangal: "No",
    gotraSurname: "Bharadwaja",
    timeOfBirth: "10:45 AM",
    partnerExpectations: ["Well-educated professional (preferably Masters) settled in metro city", "Someone who respects family values and community traditions", "Vegetarian lifestyle and non-smoker preferred", "Age preference: 28–32 years"],
    about: "A blend of traditional values and modern outlook. I value family heritage and am looking for a partner who shares similar cultural roots and life goals. Growing up in a household that balances professional excellence with cultural programming has shaped my worldview.",
    verified: true,
    matrimonialFee: true,
    avatar: "AV",
  },
  {
    id: "rohit-k",
    name: "Rohit K.",
    age: 29,
    gender: "M",
    location: "Bengaluru",
    gotra: "Kashyap",
    education: "B.Tech Computer Science, NIT Surathkal",
    company: "Infosys",
    designation: "Senior Software Engineer",
    income: "₹18–22L",
    height: "5'10\"",
    complexion: "Wheatish",
    familyType: "Joint",
    fatherOccupation: "Retired Government Officer",
    motherOccupation: "Homemaker",
    siblings: "1 Elder Sister, Married",
    star: "Uttara Phalguni",
    rashi: "Kanya",
    mangal: "No",
    gotraSurname: "Kashyap",
    timeOfBirth: "08:20 AM",
    partnerExpectations: ["Working professional from Daivagnya Samaj preferred", "Family-oriented and respects elders", "Willing to stay in Bengaluru"],
    about: "Born and raised in Bengaluru in a close-knit Samaj family. I enjoy music, trekking in the Western Ghats, and community service. Looking for a partner who values both career growth and family traditions.",
    verified: true,
    matrimonialFee: false,
    avatar: "RK",
  },
  {
    id: "sneha-p",
    name: "Sneha P.",
    age: 25,
    gender: "F",
    location: "Mumbai",
    gotra: "Vasishtha",
    education: "CA (ICAI), B.Com Mumbai University",
    company: "Deloitte India",
    designation: "Manager – Audit & Assurance",
    income: "₹20–25L",
    height: "5'3\"",
    complexion: "Fair",
    familyType: "Nuclear",
    fatherOccupation: "Business – Textile, Mangalore",
    motherOccupation: "Homemaker",
    siblings: "1 Younger Brother",
    star: "Ashwini",
    rashi: "Mesha",
    mangal: "Yes",
    gotraSurname: "Vasishtha",
    timeOfBirth: "02:30 PM",
    partnerExpectations: ["Mangalik preferred", "Settled in Mumbai or willing to relocate", "Professionally qualified (CA/MBA/Engineer)"],
    about: "A Chartered Accountant passionate about finance and heritage cooking. Weekends are for Samaj events and travel. I believe a strong marriage is built on shared values and mutual respect.",
    verified: true,
    matrimonialFee: true,
    avatar: "SP",
  },
  {
    id: "karthik-s",
    name: "Karthik S.",
    age: 28,
    gender: "M",
    location: "Hyderabad",
    gotra: "Atreya",
    education: "MBA IIM Bangalore, B.E. BITS Pilani",
    company: "Amazon",
    designation: "Senior Product Manager",
    income: "₹35–40L",
    height: "5'9\"",
    complexion: "Wheatish",
    familyType: "Nuclear",
    fatherOccupation: "Advocate, Karnataka High Court",
    motherOccupation: "Sanskrit Teacher",
    siblings: "None",
    star: "Mrigashira",
    rashi: "Mithuna",
    mangal: "No",
    gotraSurname: "Atreya",
    timeOfBirth: "06:15 PM",
    partnerExpectations: ["Educated and independent-minded", "Open to living in Hyderabad or Bengaluru", "Values Sanskrit and classical traditions"],
    about: "Product manager by day, classical Carnatic vocalist by weekend. Deeply connected to Samaj values while embracing modern professional life. Looking for a life partner who shares the joy of heritage and growth.",
    verified: true,
    matrimonialFee: false,
    avatar: "KS",
  },
]

export const WELFARE_CAMPAIGNS = [
  {
    id: "community-center",
    title: "Community Center Construction",
    category: "Infrastructure",
    description: "Construction of a multipurpose community hall for cultural programs, weddings, and community gatherings. This will be the permanent home for all Samaj activities in Bengaluru.",
    goal: 5000000,
    raised: 4250000,
    daysLeft: 12,
    backers: 328,
    image: "🏛️",
    color: "from-green-800 to-green-600",
  },
  {
    id: "annual-samaja-function",
    title: "Annual Samaja Function",
    category: "Cultural Heritage",
    description: "Funding for our flagship annual community celebration. Includes cultural performances, felicitation of elders, and scholarships for meritorious students from Samaj families.",
    goal: 2500000,
    raised: 2000000,
    daysLeft: 28,
    backers: 214,
    image: "🪔",
    color: "from-amber-800 to-amber-600",
  },
]

export const DASHBOARD_ACTIVITY = [
  { id: 1, user: "Grandma Meera", action: "shared a new story", detail: '"The Summer of 1964"', time: "2 hours ago", type: "archive", avatar: "GM" },
  { id: 2, user: "Rahul K.", action: "added Arjun V. to the", detail: "family tree", time: "3 hours ago", type: "tree", avatar: "RK" },
  { id: 3, user: "Sita Sharma", action: "has a birthday today!", detail: "", time: "Memory Celebration", type: "birthday", avatar: "SS" },
]

export const ELDER_QUEUE = [
  {
    id: "arjun-h",
    name: "Arjun Hegde",
    claimingFrom: "Shivali Branch (Udupi)",
    relation: "Grandson of Ramachandra Hegde",
    hasDocument: true,
    vouches: 0,
    avatar: "AH",
  },
  {
    id: "meera-k",
    name: "Meera Kulkarni",
    claimingFrom: "Deshastha Rigvedi (Hubli)",
    relation: "Relative vouched (3)",
    hasDocument: false,
    hasPhoto: true,
    vouches: 3,
    avatar: "MK",
  },
]
