// Daivadnya Samaj Bangalore — Demo data

export const TEST_USERS = [
  {
    phone: "9876543210", otp: "121212",
    name: "Priya Kamat", role: "member",
    gotra: "Kashyap", native: "Bengaluru, Karnataka", avatar: "6",
  },
  {
    phone: "9999999999", otp: "121212",
    name: "Shri Narayanarao Shet", role: "elder",
    gotra: "Bharadwaja", native: "Kumta, Uttara Kannada", avatar: "elder",
  },
  {
    phone: "9871234567", otp: "121212",
    name: "Akhilesh Kamat", role: "member",
    gotra: "Kashyap", native: "Udupi, Karnataka", avatar: "4",
  },
];

// Daivadnya Samaj family — goldsmith lineage from Kundapura/Kumta, now rooted in Bengaluru
export const FAMILY_MEMBERS = [
  {
    id: "1",
    name: "Ramachandra Shet",
    status: "Late",
    gotra: "Kashyap",
    native: "Kundapura, Karnataka",
    relation: "Great Grandfather",
    avatar: "RS",
    occupation: "Master Goldsmith & Jeweller",
    birthYear: "1920",
    children: ["2", "3"],
  },
  {
    id: "2",
    name: "Savitribai Shet",
    status: "Late",
    gotra: "Kashyap",
    native: "Kundapura, Karnataka",
    relation: "Great Grandmother",
    avatar: "SS",
    occupation: "Homemaker & Samaj Seva",
    birthYear: "1925",
    spouse: "1",
    children: [],
    parent: "1",
  },
  {
    id: "3",
    name: "Venkatesh Kamat",
    status: "Active",
    gotra: "Bharadwaja",
    native: "Kumta, Uttara Kannada",
    relation: "Grandfather",
    avatar: "VK",
    occupation: "Retired Jewellery Business Owner",
    birthYear: "1952",
    parent: "1",
    children: ["4", "5"],
  },
  {
    id: "4",
    name: "Suresh Kamat",
    status: "Active",
    gotra: "Kashyap",
    native: "Udupi, Karnataka",
    relation: "Father",
    avatar: "SK",
    occupation: "Senior Software Engineer, Infosys, Bengaluru",
    birthYear: "1978",
    parent: "3",
    children: ["6"],
  },
  {
    id: "5",
    name: "Rekha Pai",
    status: "Active",
    gotra: "Bharadwaja",
    native: "Mangaluru, Karnataka",
    relation: "Aunt",
    avatar: "RP",
    occupation: "Principal, Kendriya Vidyalaya, Bengaluru",
    birthYear: "1975",
    parent: "3",
    children: [],
  },
  {
    id: "6",
    name: "Priya Kamat",
    status: "Active",
    gotra: "Kashyap",
    native: "Bengaluru, Karnataka",
    relation: "Self",
    avatar: "PK",
    occupation: "UX Designer, Razorpay, Bengaluru",
    birthYear: "1999",
    parent: "4",
    children: [],
  },
];

export const MATRIMONIAL_CANDIDATES = [
  {
    id: "ananya-k",
    name: "Ananya Kamath",
    age: 27,
    gender: "F",
    location: "Bengaluru",
    gotra: "Bharadwaja",
    education: "MBA Finance, IIM Bangalore",
    company: "HDFC Bank — Wealth Management",
    designation: "Assistant Vice President",
    income: "₹22–28L",
    height: "5'4\"",
    complexion: "Wheatish",
    familyType: "Joint",
    fatherOccupation: "Jeweller & Proprietor, Kamath Gold House, Commercial Street",
    motherOccupation: "Teacher, MES College, Bengaluru",
    siblings: "1 Younger Brother, B.Tech, PESIT Bengaluru",
    star: "Rohini",
    rashi: "Vrishabha",
    mangal: "No",
    gotraSurname: "Bharadwaja",
    timeOfBirth: "10:45 AM",
    partnerExpectations: [
      "Well-educated professional from Daivadnya Samaj",
      "Preferably based in Bengaluru or Karnataka",
      "Family values and respect for Samaj traditions",
      "Age preference: 28–32 years",
    ],
    about:
      "Raised in a traditional Daivadnya Samaj family in Basavanagudi, Bengaluru. I love Carnatic music, cooking authentic Malvani cuisine, and participating in Samaj cultural events every year. Looking for a life partner who values both heritage and growth.",
    verified: true,
    matrimonialFee: true,
    avatar: "AK",
    photo: "https://randomuser.me/api/portraits/women/41.jpg",
  },
  {
    id: "rohit-s",
    name: "Rohit Shet",
    age: 30,
    gender: "M",
    location: "Bengaluru",
    gotra: "Kashyap",
    education: "B.Tech Computer Science, NIT Surathkal",
    company: "Wipro — Product Division",
    designation: "Senior Software Engineer",
    income: "₹20–25L",
    height: "5'10\"",
    complexion: "Wheatish",
    familyType: "Joint",
    fatherOccupation: "Proprietor, Shet Jewellers, Chickpete, Bengaluru",
    motherOccupation: "Homemaker",
    siblings: "1 Elder Sister, Married into Nayak family, Mangaluru",
    star: "Uttara Phalguni",
    rashi: "Kanya",
    mangal: "No",
    gotraSurname: "Kashyap",
    timeOfBirth: "08:20 AM",
    partnerExpectations: [
      "Working professional from Daivadnya Samaj",
      "Family-oriented and respects Samaj culture",
      "Comfortable with joint family in Bengaluru",
    ],
    about:
      "Born and raised in R.T. Nagar, Bengaluru. Our family has been in the jewellery business for three generations in Chickpete. I enjoy trekking in the Western Ghats and volunteering at Samaj community events. Looking for a partner who balances tradition with a modern outlook.",
    verified: true,
    matrimonialFee: false,
    avatar: "RS",
    photo: "https://randomuser.me/api/portraits/men/58.jpg",
  },
  {
    id: "sneha-n",
    name: "Sneha Naik",
    age: 25,
    gender: "F",
    location: "Mangaluru",
    gotra: "Vasishtha",
    education: "CA (ICAI), B.Com St. Aloysius College, Mangaluru",
    company: "Deloitte India — Audit",
    designation: "Deputy Manager, Audit & Assurance",
    income: "₹18–22L",
    height: "5'3\"",
    complexion: "Fair",
    familyType: "Nuclear",
    fatherOccupation: "Senior Goldsmith, Naik & Sons Jewellers, Mangaluru",
    motherOccupation: "Homemaker",
    siblings: "1 Younger Brother, CA Articleship",
    star: "Ashwini",
    rashi: "Mesha",
    mangal: "Yes",
    gotraSurname: "Vasishtha",
    timeOfBirth: "02:30 PM",
    partnerExpectations: [
      "Mangalik preferred",
      "Willing to relocate to Bengaluru or Mangaluru",
      "Professionally qualified (CA / MBA / Engineer)",
    ],
    about:
      "A first-generation CA from a proud Daivadnya Samaj family from Mangaluru. Passionate about finance, Tulu folk arts, and cooking traditional Kundapur cuisine. Weekends are for temple visits and Samaj bhajans. I believe a strong marriage rests on shared cultural roots.",
    verified: true,
    matrimonialFee: true,
    avatar: "SN",
    photo: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: "karthik-p",
    name: "Karthik Pai",
    age: 29,
    gender: "M",
    location: "Bengaluru",
    gotra: "Atreya",
    education: "MBA IIM Bangalore, B.E. R.V. College of Engineering",
    company: "Razorpay — Growth",
    designation: "Senior Product Manager",
    income: "₹32–38L",
    height: "5'9\"",
    complexion: "Wheatish",
    familyType: "Nuclear",
    fatherOccupation: "Advocate, Karnataka High Court, Bengaluru",
    motherOccupation: "Sanskrit Lecturer, Bengaluru University",
    siblings: "None",
    star: "Mrigashira",
    rashi: "Mithuna",
    mangal: "No",
    gotraSurname: "Atreya",
    timeOfBirth: "06:15 PM",
    partnerExpectations: [
      "Educated and independent-minded woman from the Samaj",
      "Based in or willing to move to Bengaluru",
      "Values Sanskrit, classical music, and Samaj traditions",
    ],
    about:
      "Raised in Jayanagar, Bengaluru — a true product of the Daivadnya Samaj diaspora. Product manager by day, Carnatic vocalist and Samaj committee volunteer by weekend. Deeply proud of my goldsmith heritage while thriving in the startup world. Looking for a life partner who loves both heritage and adventure.",
    verified: true,
    matrimonialFee: false,
    avatar: "KP",
    photo: "https://randomuser.me/api/portraits/men/20.jpg",
  },
];

export const WELFARE_CAMPAIGNS = [
  {
    id: "samaj-bhavan",
    title: "Samaj Bhavan Renovation",
    category: "Infrastructure",
    description:
      "Renovation and expansion of the Daivadnya Samaj Bhavan in Basavanagudi, Bengaluru — adding a 500-seat auditorium, digital library, and modern kitchen for community feasts.",
    goal: 5000000,
    raised: 4250000,
    daysLeft: 12,
    backers: 328,
    image: "🏛️",
    color: "from-green-800 to-green-600",
  },
  {
    id: "annual-samaja-function",
    title: "Annual Samaja Utsava 2025",
    category: "Cultural Heritage",
    description:
      "Funding for the flagship annual Samaj cultural event: classical Carnatic & Tulu performances, elder felicitation, Samaj talent showcase, and merit scholarships for 50 students.",
    goal: 2500000,
    raised: 2000000,
    daysLeft: 28,
    backers: 214,
    image: "🪔",
    color: "from-amber-800 to-amber-600",
  },
  {
    id: "student-scholarship",
    title: "Daivadnya Vidya Nidhi — Scholarships",
    category: "Education",
    description:
      "Merit-cum-need scholarships for Samaj students pursuing engineering, medicine, and law. 30 scholarships of ₹50,000 each for the academic year 2025–26.",
    goal: 1500000,
    raised: 875000,
    daysLeft: 45,
    backers: 167,
    image: "🎓",
    color: "from-blue-900 to-blue-700",
  },
];

export const DASHBOARD_ACTIVITY = [
  {
    id: 1,
    user: "Venkatesh Kamat",
    action: "shared a memory",
    detail: '"1968 Samaj Utsava in Kumta"',
    time: "2 hours ago",
    type: "archive",
    avatar: "VK",
    photo: "https://randomuser.me/api/portraits/men/70.jpg",
  },
  {
    id: 2,
    user: "Shri Narayanarao Shet",
    action: "verified the lineage of",
    detail: "Rohit Shet — Chickpete branch",
    time: "Yesterday",
    type: "tree",
    avatar: "NS",
    photo: "https://randomuser.me/api/portraits/men/64.jpg",
  },
  {
    id: 3,
    user: "Rekha Pai",
    action: "has a birthday today!",
    detail: "Wishing her from the Samaj 🎉",
    time: "Today",
    type: "birthday",
    avatar: "RP",
    photo: "https://randomuser.me/api/portraits/women/54.jpg",
  },
];

export const ELDER_QUEUE = [
  {
    id: "arjun-s",
    name: "Arjun Shenoy",
    claimingFrom: "Kundapura Branch (Udupi District)",
    relation: "Grandson of Late Govind Shenoy (Kundapura)",
    hasDocument: true,
    vouches: 2,
    avatar: "AS",
  },
  {
    id: "divya-n",
    name: "Divya Nayak",
    claimingFrom: "Kumta Branch (Uttara Kannada)",
    relation: "Daughter of Prakash Nayak (3 elder vouches pending)",
    hasDocument: false,
    hasPhoto: true,
    vouches: 3,
    avatar: "DN",
  },
];
